# Generate language entries for all new blocks
$allBlocks = @(
    # Dreaming Depths
    @{name="dreamstone"; display="Dreamstone"},
    @{name="lullglass"; display="Lullglass"},
    @{name="softsoil"; display="Softsoil"},
    @{name="dreamgrass"; display="Dreamgrass"},
    @{name="nightbloom_vine"; display="Nightbloom Vine"},
    @{name="echo_crystal"; display="Echo Crystal"},
    @{name="phantasm_dust"; display="Phantasm Dust"},
    @{name="etherstone"; display="Etherstone"},
    @{name="mirage_leaf"; display="Mirage Leaf"},
    @{name="dreamwood_log"; display="Dreamwood Log"},
    @{name="lucid_flower"; display="Lucid Flower"},
    @{name="glowsand"; display="Glowsand"},
    @{name="glowglass"; display="Glowglass"},
    @{name="memory_stone"; display="Memory Stone"},
    @{name="levistone"; display="Levistone"},
    @{name="dreamroot"; display="Dreamroot"},
    @{name="reverie_crystal"; display="Reverie Crystal"},
    @{name="whisper_wool"; display="Whisper Wool"},
    @{name="dreamlight_lantern"; display="Dreamlight Lantern"},
    # Celestine Expanse
    @{name="celestine_grass"; display="Celestine Grass"},
    @{name="starlit_stone"; display="Starlit Stone"},
    @{name="lumicore_block"; display="Lumicore Block"},
    @{name="aurora_root"; display="Aurora Root"},
    @{name="astral_glass"; display="Astral Glass"},
    @{name="nimbus_dust"; display="Nimbus Dust"},
    @{name="aether_stone"; display="Aether Stone"},
    @{name="void_coral"; display="Void Coral"},
    @{name="radiant_crystal"; display="Radiant Crystal"},
    @{name="feather_reed"; display="Feather Reed"},
    @{name="starfall_ore"; display="Starfall Ore"},
    @{name="luminite_lantern"; display="Luminite Lantern"},
    @{name="aural_moss"; display="Aural Moss"},
    @{name="celestine_brick"; display="Celestine Brick"},
    @{name="celestine_tile"; display="Celestine Tile"},
    @{name="starlight_pane"; display="Starlight Pane"},
    @{name="aether_sand"; display="Aether Sand"},
    @{name="lumicore_lamp"; display="Lumicore Lamp"},
    @{name="crystal_vine"; display="Crystal Vine"},
    @{name="celestine_ore"; display="Celestine Ore"},
    # Fungal Dominion
    @{name="mycelite_soil"; display="Mycelite Soil"},
    @{name="root_flesh"; display="Root Flesh"},
    @{name="biolume_cap"; display="Biolume Cap"},
    @{name="spore_pod"; display="Spore Pod"},
    @{name="fungal_vein"; display="Fungal Vein"},
    @{name="decay_clay"; display="Decay Clay"},
    @{name="calcimoss_block"; display="Calcimoss Block"},
    @{name="lumispore_cluster"; display="Lumispore Cluster"},
    @{name="fungal_bark"; display="Fungal Bark"},
    @{name="mycelite_brick"; display="Mycelite Brick"},
    @{name="fungal_glass"; display="Fungal Glass"},
    @{name="symbiont_root"; display="Symbiont Root"},
    @{name="fungal_vine"; display="Fungal Vine"},
    @{name="mold_cap_carpet"; display="Mold Cap Carpet"},
    @{name="root_heart_block"; display="Root Heart Block"},
    @{name="fossil_bark"; display="Fossil Bark"},
    @{name="sporelight"; display="Sporelight"},
    @{name="fungal_moss"; display="Fungal Moss"},
    @{name="spore_web"; display="Spore Web"},
    # Forgotten Archive
    @{name="runestone"; display="Runestone"},
    @{name="runestone_brick"; display="Runestone Brick"},
    @{name="archive_sandstone"; display="Archive Sandstone"},
    @{name="mirror_tile"; display="Mirror Tile"},
    @{name="ink_marble"; display="Ink Marble"},
    @{name="memory_ink_block"; display="Memory Ink Block"},
    @{name="glyph_glass"; display="Glyph Glass"},
    @{name="runic_pedestal"; display="Runic Pedestal"},
    @{name="ink_carpet"; display="Ink Carpet"},
    @{name="engraved_gold"; display="Engraved Gold"},
    @{name="archive_plank"; display="Archive Plank"},
    @{name="knowledge_crystal"; display="Knowledge Crystal"},
    @{name="dust_sand"; display="Dust Sand"},
    @{name="runic_lantern"; display="Runic Lantern"},
    @{name="inscribed_bookcase"; display="Inscribed Bookcase"},
    @{name="runestone_slab"; display="Runestone Slab"},
    @{name="runic_gate"; display="Runic Gate"},
    @{name="fossil_tablet"; display="Fossil Tablet"},
    @{name="script_light"; display="Script Light"},
    # Astral Frontier
    @{name="starlit_grass_af"; display="Starlit Grass"},
    @{name="stardust_stone"; display="Stardust Stone"},
    @{name="celestite_block"; display="Celestite Block"},
    @{name="celestite_crystal"; display="Celestite Crystal"},
    @{name="stardust_ore"; display="Stardust Ore"},
    @{name="nebular_dust"; display="Nebular Dust"},
    @{name="aether_core"; display="Aether Core"},
    @{name="singularity_rock"; display="Singularity Rock"},
    @{name="astral_glass_af"; display="Astral Glass"},
    @{name="starlight_vine"; display="Starlight Vine"},
    @{name="voidroot"; display="Voidroot"},
    @{name="astral_lantern"; display="Astral Lantern"},
    @{name="stardust_sand"; display="Stardust Sand"},
    @{name="astral_ice"; display="Astral Ice"},
    @{name="celestial_alloy_block"; display="Celestial Alloy Block"},
    @{name="astral_conduit"; display="Astral Conduit"},
    # Gloomy Caverns
    @{name="withered_basalt"; display="Withered Basalt"},
    @{name="echo_stone"; display="Echo Stone"},
    @{name="drip_moss"; display="Drip Moss"},
    @{name="decay_soil"; display="Decay Soil"},
    @{name="gloom_crystal"; display="Gloom Crystal"},
    @{name="fungal_bark_gloomy"; display="Fungal Bark"},
    @{name="bone_brick"; display="Bone Brick"},
    @{name="echo_lantern"; display="Echo Lantern"},
    @{name="mourn_vine"; display="Mourn Vine"}
)
$langEntries = ""
foreach ($block in $allBlocks) {
    $langEntries += ",`n  `"block.elementaldimensions.$($block.name)`": `"$($block.display)`""
}
Write-Output $langEntries